import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import * as lib from 'pdf-lib';
import fs from 'fs';
import { removeText } from './src/pdfText.js';
const [file, out] = process.argv.slice(2);
const bytes = fs.readFileSync(file);
const d = await pdfjs.getDocument({ data: new Uint8Array(bytes) }).promise;
const pg = await d.getPage(1); const tc = await pg.getTextContent();
const items = tc.items.filter(i => i.str.trim());
const pick = items.filter((_, k) => [1, 3, 5].includes(k));
console.log('removing:', pick.map(i => i.str));
const boxes = pick.map((it, k) => { const [a, b, c, dd, e, f] = it.transform; const st = tc.styles[it.fontName]; return { id: k, x: e, y: f, angle: Math.atan2(b, a), width: it.width, size: Math.hypot(c, dd), ascent: st.ascent || 0.8, descent: st.descent || -0.2 }; });
const doc = await lib.PDFDocument.load(bytes);
const clean = removeText(lib, doc.getPage(0), boxes);
console.log('clean:', [...clean]);
fs.writeFileSync(out, await doc.save());
const d2 = await pdfjs.getDocument({ data: new Uint8Array(fs.readFileSync(out)) }).promise;
const tc2 = await (await d2.getPage(1)).getTextContent();
const left = tc2.items.filter(i => i.str.trim());
console.log('before', items.length, 'after', left.length);
const pos = new Map(items.map(i => [i.str, i.transform.slice(4).map(Math.round).join(',')]));
console.log('moved:', left.filter(i => pos.get(i.str) !== i.transform.slice(4).map(Math.round).join(',')).map(i => i.str));
